import { useState, type FormEvent } from 'react';
import { Link, useLocation } from 'wouter';
import { ArrowLeft, Check, ChevronDown, Info, Plus, Save, Trash2 } from 'lucide-react';
import { useCreateAlert, getListAlertsQueryKey, getGetDashboardSummaryQueryKey, type AlertInput, AlertInputChannelsItem, AlertInputSeverity, AlertInputType } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { AppShell, SectionHeading, channelLabels } from '@/components/platform';

const initial: AlertInput = { title: '', message: '', type: 'flood', severity: 'warning', location: '', affectedAreas: [''], instructions: [''], channels: ['web', 'sms'], expiresAt: new Date(Date.now() + 86400000).toISOString().slice(0, 16), source: 'North Coast Emergency Coordination Cell' };
const types: AlertInputType[] = ['flood', 'cyclone', 'earthquake', 'wildfire', 'heatwave', 'other'];
const severities: AlertInputSeverity[] = ['advisory', 'warning', 'critical'];
const channels: AlertInputChannelsItem[] = ['web', 'sms', 'push', 'siren', 'radio'];

export default function AlertForm() {
  const [, navigate] = useLocation();
  const queryClient = useQueryClient();
  const create = useCreateAlert();
  const [form, setForm] = useState<AlertInput>(initial);
  const [error, setError] = useState('');
  const set = <K extends keyof AlertInput>(key: K, value: AlertInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  const setList = (key: 'affectedAreas' | 'instructions', index: number, value: string) => setForm((current) => ({ ...current, [key]: current[key].map((item, i) => i === index ? value : item) }));
  const addList = (key: 'affectedAreas' | 'instructions') => setForm((current) => ({ ...current, [key]: [...current[key], ''] }));
  const removeList = (key: 'affectedAreas' | 'instructions', index: number) => setForm((current) => ({ ...current, [key]: current[key].filter((_, i) => i !== index) }));
  const toggleChannel = (channel: AlertInputChannelsItem) => set('channels', form.channels.includes(channel) ? form.channels.filter((item) => item !== channel) : [...form.channels, channel]);
  const submit = (event: FormEvent) => {
    event.preventDefault(); setError('');
    const payload = { ...form, affectedAreas: form.affectedAreas.filter(Boolean), instructions: form.instructions.filter(Boolean) };
    if (payload.title.trim().length < 3 || payload.message.trim().length < 10 || !payload.location.trim() || !payload.affectedAreas.length || !payload.instructions.length || !payload.channels.length) { setError('Complete the required fields before saving this draft.'); return; }
    create.mutate({ data: payload }, { onSuccess: (alert) => { queryClient.invalidateQueries({ queryKey: getListAlertsQueryKey({ status: 'all' }) }); queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); navigate(`/console/alerts/${alert.id}`); }, onError: () => setError('Draft could not be saved. Check the network and try again.') });
  };
  return <AppShell authority><div className="mx-auto max-w-[1050px] px-5 py-9 lg:px-8 lg:py-12"><Link href="/console" className="mb-8 inline-flex items-center gap-2 text-xs font-bold text-muted-foreground hover:text-primary" data-testid="link-back-console"><ArrowLeft size={14} /> Operations desk</Link><SectionHeading eyebrow="New broadcast · draft" title="Compose an alert" detail="Write for the person reading this on a difficult day. Be specific, direct, and useful." />
    <form onSubmit={submit} className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="space-y-5"><section className="card-surface rounded-xl p-5 sm:p-7"><div className="mb-6 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground font-mono text-xs">01</span><div><h2 className="font-extrabold">The signal</h2><p className="text-xs text-muted-foreground">What people need to know immediately.</p></div></div><label className="mb-4 block text-xs font-extrabold">Headline <span className="text-accent">*</span><input value={form.title} onChange={(e) => set('title', e.target.value)} className="field mt-2" placeholder="e.g. Evacuate low-lying areas near River Rhea" data-testid="input-alert-title" /></label><label className="block text-xs font-extrabold">Message <span className="text-accent">*</span><textarea value={form.message} onChange={(e) => set('message', e.target.value)} className="field mt-2 min-h-[150px] resize-y leading-relaxed" placeholder="State what is happening, where, and what people should expect." data-testid="input-alert-message" /><span className="mt-1 block text-right font-mono text-[10px] text-muted-foreground">{form.message.length} characters</span></label></section>
      <section className="card-surface rounded-xl p-5 sm:p-7"><div className="mb-6 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground font-mono text-xs">02</span><div><h2 className="font-extrabold">Scope and response</h2><p className="text-xs text-muted-foreground">Help people locate themselves and choose a next step.</p></div></div><label className="mb-4 block text-xs font-extrabold">Location <span className="text-accent">*</span><input value={form.location} onChange={(e) => set('location', e.target.value)} className="field mt-2" placeholder="e.g. River Rhea basin, North Coast" data-testid="input-alert-location" /></label><ListEditor label="Affected areas" items={form.affectedAreas} onChange={(i, v) => setList('affectedAreas', i, v)} onAdd={() => addList('affectedAreas')} onRemove={(i) => removeList('affectedAreas', i)} placeholder="Town, district, or landmark" testId="affected-area" /><ListEditor label="Instructions" items={form.instructions} onChange={(i, v) => setList('instructions', i, v)} onAdd={() => addList('instructions')} onRemove={(i) => removeList('instructions', i)} placeholder="A clear action people can take now" testId="instruction" /></section></div>
      <aside className="space-y-5"><section className="card-surface rounded-xl p-5"><p className="eyebrow mb-4">Classification</p><FieldSelect label="Alert type" value={form.type} onChange={(v) => set('type', v as AlertInputType)} options={types} testId="select-alert-type" /><FieldSelect label="Severity" value={form.severity} onChange={(v) => set('severity', v as AlertInputSeverity)} options={severities} testId="select-alert-severity" /><label className="mt-4 block text-xs font-extrabold">Expires at<input type="datetime-local" value={form.expiresAt} onChange={(e) => set('expiresAt', e.target.value)} className="field mt-2" data-testid="input-alert-expiry" /></label></section><section className="card-surface rounded-xl p-5"><p className="eyebrow mb-4">Distribution</p><div className="space-y-2">{channels.map((channel) => <button type="button" key={channel} onClick={() => toggleChannel(channel)} className={`flex w-full items-center justify-between rounded-lg border px-3 py-2.5 text-xs font-bold ${form.channels.includes(channel) ? 'border-primary bg-primary/8 text-primary' : 'border-border text-muted-foreground'}`} data-testid={`button-channel-${channel}`}><span>{channelLabels[channel]}</span>{form.channels.includes(channel) && <Check size={14} />}</button>)}</div><p className="mt-4 flex gap-2 text-[10px] leading-relaxed text-muted-foreground"><Info size={14} className="shrink-0 text-primary" /> Channels are activated when this draft is published.</p></section><section className="rounded-xl border border-primary/20 bg-secondary/55 p-5"><p className="eyebrow mb-2">Source of record</p><input value={form.source} onChange={(e) => set('source', e.target.value)} className="field bg-card" data-testid="input-alert-source" /></section>{error && <p className="rounded-lg bg-accent/10 p-3 text-xs font-bold text-accent" data-testid="text-form-error">{error}</p>}<button type="submit" className="btn btn-accent w-full py-3" disabled={create.isPending} data-testid="button-save-draft"><Save size={15} />{create.isPending ? 'Saving draft…' : 'Save draft'}</button></aside></form>
  </div></AppShell>;
}

function FieldSelect({ label, value, onChange, options, testId }: { label: string; value: string; onChange: (value: string) => void; options: string[]; testId: string }) {
  return <label className="mb-4 block text-xs font-extrabold last:mb-0">{label}<span className="relative mt-2 block"><select value={value} onChange={(e) => onChange(e.target.value)} className="field appearance-none pr-8 capitalize" data-testid={testId}>{options.map((option) => <option value={option} key={option}>{option}</option>)}</select><ChevronDown size={14} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground" /></span></label>;
}
function ListEditor({ label, items, onChange, onAdd, onRemove, placeholder, testId }: { label: string; items: string[]; onChange: (index: number, value: string) => void; onAdd: () => void; onRemove: (index: number) => void; placeholder: string; testId: string }) {
  return <div className="mb-5 last:mb-0"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-extrabold">{label} <span className="text-accent">*</span></span><button type="button" onClick={onAdd} className="flex items-center gap-1 text-[10px] font-extrabold text-primary" data-testid={`button-add-${testId}`}><Plus size={13} /> Add</button></div><div className="space-y-2">{items.map((item, index) => <div className="flex gap-2" key={`${testId}-${index}`}><input value={item} onChange={(e) => onChange(index, e.target.value)} className="field" placeholder={placeholder} data-testid={`input-${testId}-${index}`} />{items.length > 1 && <button type="button" onClick={() => onRemove(index)} className="btn btn-ghost shrink-0 p-2 text-muted-foreground hover:text-accent" aria-label={`Remove ${label}`} data-testid={`button-remove-${testId}-${index}`}><Trash2 size={14} /></button>}</div>)}</div></div>;
}