import { useEffect, useState, type Dispatch, type SetStateAction } from 'react';
import { Link, useLocation, useParams } from 'wouter';
import { ArrowLeft, Check, Edit3, Radio, Save, Send, ShieldCheck, TriangleAlert } from 'lucide-react';
import { useGetAlert, getGetAlertQueryKey, useGetAlertDelivery, getGetAlertDeliveryQueryKey, useUpdateAlert, usePublishAlert, getListAlertsQueryKey, getGetDashboardSummaryQueryKey, type AlertUpdate, type Alert, type DeliveryMetrics } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { AlertBadge, AppShell, ChannelPills, DetailPanel, ErrorBlock, LoadingBlock, ProgressBar, SectionHeading, channelLabels, dateLabel } from '@/components/platform';

export default function AlertReview() {
  const { id = '' } = useParams<{ id: string }>();
  const [, navigate] = useLocation();
  const queryClient = useQueryClient();
  const alertQuery = useGetAlert(id, { query: { queryKey: getGetAlertQueryKey(id), refetchInterval: 30000 } });
  const deliveryQuery = useGetAlertDelivery(id, { query: { queryKey: getGetAlertDeliveryQueryKey(id), refetchInterval: 15000 } });
  const update = useUpdateAlert(); const publish = usePublishAlert();
  const alert = alertQuery.data;
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState<AlertUpdate>({});
  const [notice, setNotice] = useState('');
  useEffect(() => { if (alert) setDraft({ title: alert.title, message: alert.message, severity: alert.severity, location: alert.location, affectedAreas: alert.affectedAreas, instructions: alert.instructions, channels: alert.channels, expiresAt: alert.expiresAt }); }, [alert]);
  if (alertQuery.isLoading) return <AppShell authority><div className="mx-auto max-w-[1100px] px-5 py-12 lg:px-8"><LoadingBlock label="Loading alert record" /></div></AppShell>;
  if (alertQuery.isError || !alert) return <AppShell authority><div className="mx-auto max-w-[1100px] px-5 py-12 lg:px-8"><ErrorBlock onRetry={() => alertQuery.refetch()} /></div></AppShell>;
  const save = () => update.mutate({ id, data: draft }, { onSuccess: (saved) => { queryClient.setQueryData(getGetAlertQueryKey(id), saved); queryClient.invalidateQueries({ queryKey: getListAlertsQueryKey({ status: 'all' }) }); setEditing(false); setNotice('Changes saved'); setTimeout(() => setNotice(''), 2500); }, onError: () => setNotice('Changes could not be saved') });
  const doPublish = () => { if (!window.confirm('Publish this alert to the selected channels?')) return; publish.mutate({ id }, { onSuccess: (published) => { queryClient.setQueryData(getGetAlertQueryKey(id), published); queryClient.invalidateQueries({ queryKey: getListAlertsQueryKey({ status: 'all' }) }); queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); setNotice('Alert published to the network'); setTimeout(() => setNotice(''), 2500); }, onError: () => setNotice('Publishing failed. No channels were changed.') }); };
  return <AppShell authority><div className="mx-auto max-w-[1100px] px-5 py-9 lg:px-8 lg:py-12"><Link href="/console" className="mb-8 inline-flex items-center gap-2 text-xs font-bold text-muted-foreground hover:text-primary" data-testid="link-back-console"><ArrowLeft size={14} /> Operations desk</Link><SectionHeading eyebrow={`${alert.status === 'draft' ? 'Review draft' : 'Alert record'} · ${alert.id}`} title={alert.title} detail={`${alert.location} · created ${dateLabel(alert.createdAt)}`} action={<div className="flex gap-2">{alert.status === 'draft' && !editing && <button className="btn btn-ghost" onClick={() => setEditing(true)} data-testid="button-edit-alert"><Edit3 size={14} /> Edit</button>}{editing && <button className="btn btn-ghost" onClick={() => setEditing(false)} data-testid="button-cancel-edit">Cancel</button>}{editing ? <button className="btn btn-primary" onClick={save} disabled={update.isPending} data-testid="button-save-alert"><Save size={14} /> Save changes</button> : alert.status === 'draft' && <button className="btn btn-accent" onClick={doPublish} disabled={publish.isPending} data-testid="button-publish-alert"><Send size={14} /> Publish alert</button>}</div>} />
    {notice && <div className="mb-5 flex items-center gap-2 rounded-lg border border-primary/20 bg-primary/8 p-3 text-xs font-bold text-primary" data-testid="status-action-notice"><Check size={15} /> {notice}</div>}
    {editing ? <EditPanel draft={draft} setDraft={setDraft} /> : <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><div className="space-y-5"><DetailPanel alert={alert} onClose={() => navigate('/console')} /><DeliveryPanel delivery={deliveryQuery.data} loading={deliveryQuery.isLoading} /></div><ReviewRail alert={alert} delivery={deliveryQuery.data} onPublish={doPublish} publishing={publish.isPending} /></div>}
  </div></AppShell>;
}

function DeliveryPanel({ delivery, loading }: { delivery?: DeliveryMetrics; loading: boolean }) {
  return <section className="card-surface rounded-xl p-5 sm:p-7"><div className="mb-6 flex items-center justify-between"><div><p className="eyebrow mb-2">Delivery inspection</p><h2 className="text-lg font-extrabold">Channel performance</h2></div><Radio size={18} className="text-primary" /></div>{loading ? <LoadingBlock label="Refreshing delivery metrics" /> : delivery ? <><div className="grid grid-cols-3 gap-3">{[['Audience', delivery.audience.toLocaleString()], ['Delivered', delivery.delivered.toLocaleString()], ['Acknowledged', delivery.acknowledged.toLocaleString()]].map(([label, value]) => <div className="rounded-lg bg-secondary/60 p-3" key={label}><p className="font-mono text-[10px] text-muted-foreground">{label}</p><p className="mt-2 text-xl font-extrabold">{value}</p></div>)}</div><div className="mt-6 space-y-4">{delivery.channels.map((channel) => <div className="flex items-center gap-3" key={channel.channel}><div className="w-14 text-xs font-bold">{channelLabels[channel.channel]}</div><ProgressBar {...channel} /><span className="ml-auto font-mono text-[10px] text-muted-foreground">{channel.delivered.toLocaleString()} / {channel.total.toLocaleString()}</span></div>)}</div><p className="mt-5 border-t border-border pt-4 font-mono text-[10px] text-muted-foreground">Last updated {dateLabel(delivery.lastUpdated)}</p></> : <p className="text-sm text-muted-foreground">Delivery metrics will appear once this alert is published.</p>}</section>;
}
function ReviewRail({ alert, delivery, onPublish, publishing }: { alert: Alert; delivery?: DeliveryMetrics; onPublish: () => void; publishing: boolean }) {
  return <aside className="space-y-5"><section className="card-surface rounded-xl p-5"><div className="flex items-center gap-2"><AlertBadge severity={alert.severity} status={alert.status} /></div><div className="mt-5 space-y-4 text-xs"><div className="flex justify-between gap-3"><span className="text-muted-foreground">Source</span><strong className="text-right">{alert.source}</strong></div><div className="flex justify-between gap-3"><span className="text-muted-foreground">Expires</span><strong>{dateLabel(alert.expiresAt)}</strong></div><div className="flex justify-between gap-3"><span className="text-muted-foreground">Channels</span><span className="text-right"><ChannelPills channels={alert.channels} /></span></div></div></section>{alert.status === 'draft' && <section className="rounded-xl border border-accent/25 bg-accent/8 p-5"><div className="flex items-center gap-2 text-sm font-extrabold"><TriangleAlert size={16} className="text-accent" /> Ready to publish?</div><p className="mt-3 text-xs leading-relaxed text-muted-foreground">Publishing sends this message to every selected channel. Confirm the scope and expiry before you proceed.</p><button className="btn btn-accent mt-5 w-full" onClick={onPublish} disabled={publishing} data-testid="button-publish-rail"><Send size={14} />{publishing ? 'Publishing…' : 'Publish to network'}</button></section>}<div className="rounded-xl bg-secondary/60 p-5"><div className="flex items-center gap-2 text-xs font-extrabold"><ShieldCheck size={15} className="text-primary" /> Audit-safe record</div><p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">All edits are attributed to the coordination cell and reflected across public views.</p></div></aside>;
}
function EditPanel({ draft, setDraft }: { draft: AlertUpdate; setDraft: Dispatch<SetStateAction<AlertUpdate>> }) {
  const set = <K extends keyof AlertUpdate>(key: K, value: AlertUpdate[K]) => setDraft((current) => ({ ...current, [key]: value }));
  return <div className="card-surface rounded-xl p-5 sm:p-7"><div className="mb-6 flex items-center gap-2 text-sm font-extrabold"><Edit3 size={16} className="text-primary" /> Editing draft</div><div className="space-y-5"><label className="block text-xs font-extrabold">Headline<input value={draft.title ?? ''} onChange={(e) => set('title', e.target.value)} className="field mt-2" data-testid="input-edit-title" /></label><label className="block text-xs font-extrabold">Message<textarea value={draft.message ?? ''} onChange={(e) => set('message', e.target.value)} className="field mt-2 min-h-[170px]" data-testid="input-edit-message" /></label><label className="block text-xs font-extrabold">Location<input value={draft.location ?? ''} onChange={(e) => set('location', e.target.value)} className="field mt-2" data-testid="input-edit-location" /></label><label className="block text-xs font-extrabold">Expiry<input type="datetime-local" value={draft.expiresAt ? draft.expiresAt.slice(0, 16) : ''} onChange={(e) => set('expiresAt', e.target.value)} className="field mt-2" data-testid="input-edit-expiry" /></label></div></div>;
}