import { Link } from 'wouter';
import { Activity, ArrowUpRight, CheckCircle2, ChevronRight, Clock3, Megaphone, Plus, Radio, ShieldAlert, Signal, UsersRound } from 'lucide-react';
import { useGetDashboardSummary, getGetDashboardSummaryQueryKey, useListAlerts, getListAlertsQueryKey } from '@workspace/api-client-react';
import { AppShell, AlertBadge, AlertTypeIcon, EmptyBlock, ErrorBlock, LoadingBlock, ProgressBar, SectionHeading, compactNumber, dateLabel, timeAgo, typeMeta } from '@/components/platform';

export default function ConsoleOverview() {
  const summaryQuery = useGetDashboardSummary({ query: { queryKey: getGetDashboardSummaryQueryKey(), refetchInterval: 30000 } });
  const alertsQuery = useListAlerts({ status: 'all' }, { query: { queryKey: getListAlertsQueryKey({ status: 'all' }), refetchInterval: 30000 } });
  const summary = summaryQuery.data;
  const activeAlerts = (alertsQuery.data ?? []).filter((alert) => alert.status === 'active');
  return <AppShell authority><div className="mx-auto max-w-[1220px] px-5 py-9 lg:px-8 lg:py-12">
    <SectionHeading eyebrow="Tuesday · 08:42 local" title="Operations desk" detail="A quiet surface for a fast-moving network. Monitor the signal, then publish with confidence." action={<Link href="/console/alerts/new" className="btn btn-accent" data-testid="button-new-alert"><Plus size={16} /> New alert</Link>} />
    {summaryQuery.isLoading || alertsQuery.isLoading ? <LoadingBlock label="Loading operations snapshot" /> : summaryQuery.isError || alertsQuery.isError ? <ErrorBlock onRetry={() => { summaryQuery.refetch(); alertsQuery.refetch(); }} /> : <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Active alerts" value={String(summary?.activeAlerts ?? activeAlerts.length)} detail="currently broadcasting" icon={ShieldAlert} accent="text-accent" /><Metric label="People reached" value={compactNumber(summary?.peopleReached)} detail="across all channels" icon={UsersRound} accent="text-primary" /><Metric label="Delivery rate" value={`${summary?.deliveryRate ?? 0}%`} detail="last 24 hours" icon={Signal} accent="text-[hsl(150_48%_43%)]" /><Metric label="Acknowledgements" value={compactNumber(summary?.acknowledgements)} detail="confirmed received" icon={CheckCircle2} accent="text-primary" /></div>
      <div className="mt-8 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="card-surface rounded-xl p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="eyebrow mb-2">Broadcasting now</p><h2 className="text-lg font-extrabold">Active alerts</h2></div><Link href="/console/alerts/new" className="btn btn-ghost" data-testid="button-publish-from-overview"><Megaphone size={14} /> Publish</Link></div>{activeAlerts.length === 0 ? <EmptyBlock title="No alerts in flight" body="The network is clear. Create a draft when a verified situation needs public action." /> : <div className="divide-y divide-border">{activeAlerts.slice(0, 5).map((alert) => <Link href={`/console/alerts/${alert.id}`} key={alert.id} className="group flex items-center gap-4 py-4 first:pt-0 last:pb-0" data-testid={`row-active-alert-${alert.id}`}><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-secondary text-primary"><AlertTypeIcon type={alert.type} /></div><div className="min-w-0 flex-1"><div className="mb-1 flex items-center gap-2"><AlertBadge severity={alert.severity} status={alert.status} /><span className="truncate text-[11px] text-muted-foreground">{alert.location}</span></div><p className="truncate text-sm font-bold group-hover:text-primary">{alert.title}</p></div><div className="hidden text-right sm:block"><p className="font-mono text-[10px] text-muted-foreground">{timeAgo(alert.publishedAt)}</p><p className="mt-1 text-[10px] text-muted-foreground">{alert.delivery ? `${Math.round((alert.delivery.delivered / Math.max(alert.delivery.audience, 1)) * 100)}% delivered` : 'Delivery pending'}</p></div><ChevronRight size={15} className="text-muted-foreground transition-transform group-hover:translate-x-0.5" /></Link>)}</div>}</section>
        <section className="card-surface rounded-xl p-5 sm:p-6"><div className="mb-6 flex items-center justify-between"><div><p className="eyebrow mb-2">Channel health</p><h2 className="text-lg font-extrabold">Delivery fabric</h2></div><Radio size={18} className="text-primary" /></div><div className="space-y-5">{(summary?.channelHealth ?? []).map((channel) => <div key={channel.channel} className="flex items-center gap-3"><div className="w-12 text-xs font-bold">{channel.channel.toUpperCase()}</div><ProgressBar {...channel} /><div className="ml-auto font-mono text-[10px] text-muted-foreground">{channel.delivered.toLocaleString()}</div></div>)}</div><div className="mt-7 flex items-center gap-2 border-t border-border pt-4 text-[10px] font-bold text-[hsl(150_48%_43%)]"><span className="h-1.5 w-1.5 rounded-full bg-current" /> All channel systems operational</div></section></div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><section className="card-surface rounded-xl p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="eyebrow mb-2">Recent activity</p><h2 className="text-lg font-extrabold">Network log</h2></div><Activity size={18} className="text-primary" /></div><div className="space-y-4">{(summary?.recentActivity ?? []).slice(0, 5).map((event) => <div key={event.id} className="flex gap-3"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${event.severity === 'critical' ? 'bg-accent' : event.severity === 'warning' ? 'bg-[hsl(38_85%_55%)]' : 'bg-primary'}`} /><div><p className="text-xs font-bold">{event.action}</p><p className="mt-0.5 text-xs text-muted-foreground">{event.detail}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{timeAgo(event.time)}</p></div></div>)}</div></section><section className="rounded-xl bg-secondary/70 p-6"><p className="eyebrow mb-3">Publishing checklist</p><h2 className="display-type max-w-md text-2xl font-extrabold">The right message, to the right people, at the right time.</h2><div className="mt-6 space-y-3">{['Confirm the source is accountable', 'Name the affected area precisely', 'Give people a clear next action', 'Set an expiry before you publish'].map((item) => <div key={item} className="flex items-center gap-3 text-xs font-bold"><CheckCircle2 size={15} className="text-primary" />{item}</div>)}</div><Link href="/console/alerts/new" className="btn btn-primary mt-7" data-testid="button-start-draft">Start a draft <ArrowUpRight size={14} /></Link></section></div></>}
  </div></AppShell>;
}

function Metric({ label, value, detail, icon: Icon, accent }: { label: string; value: string; detail: string; icon: typeof Activity; accent: string }) {
  return <div className="card-surface rounded-xl p-5"><div className="flex items-start justify-between"><p className="text-xs font-bold text-muted-foreground">{label}</p><Icon size={17} className={accent} /></div><p className="display-type mt-5 text-3xl font-extrabold">{value}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{detail}</p></div>;
}