import { useMemo, useState } from 'react';
import { ArrowUpRight, Filter, Info, MapPinned, Search } from 'lucide-react';
import { useListAlerts, getListAlertsQueryKey, type Alert } from '@workspace/api-client-react';
import { Link } from 'wouter';
import { AlertBadge, AppShell, DetailPanel, EmptyBlock, ErrorBlock, LoadingBlock, PublicAlertCard, SectionHeading, typeMeta } from '@/components/platform';

export default function PublicHome() {
  const [selected, setSelected] = useState<Alert | null>(null);
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');
  const params = useMemo(() => ({ status: 'active' as const, ...(filter !== 'all' ? { audience: filter } : {}), ...(search ? { search } : {}) }), [filter, search]);
  const query = useListAlerts(params, { query: { queryKey: getListAlertsQueryKey(params), refetchInterval: 30000 } });
  const alerts = query.data ?? [];
  return <AppShell><div className="mx-auto max-w-[1240px] px-5 pb-20 pt-10 lg:px-8 lg:pt-16">
    <section className="relative overflow-hidden rounded-2xl border border-border bg-primary px-6 py-10 text-primary-foreground sm:px-10 sm:py-14"><div className="absolute -right-28 -top-32 h-80 w-80 rounded-full border-[34px] border-accent/35" /><div className="absolute -bottom-40 right-24 h-72 w-72 rounded-full border border-primary-foreground/15" /><div className="relative max-w-2xl"><p className="eyebrow text-accent">Public alert network · live feed</p><h1 className="display-type mt-4 text-4xl font-extrabold leading-[.98] tracking-[-.06em] sm:text-6xl">Know what matters.<br /><span className="text-accent">Act with clarity.</span></h1><p className="mt-6 max-w-xl text-sm leading-7 text-primary-foreground/75 sm:text-base">Verified emergency information for the North Coast. No speculation, no noise — just the signal you can act on.</p><div className="mt-8 flex flex-wrap items-center gap-3"><div className="flex items-center gap-2 rounded-full bg-primary-foreground/10 px-3 py-2 font-mono text-[10px]"><span className="pulse-dot h-1.5 w-1.5 rounded-full bg-accent" /> Live updates every 30 seconds</div><Link href="/console" className="flex items-center gap-1 text-xs font-bold text-primary-foreground/80 hover:text-accent" data-testid="link-coordinator-access">For coordinators <ArrowUpRight size={14} /></Link></div></div></section>
    <div className="mt-12 grid gap-10 lg:grid-cols-[1fr_330px]"><div><SectionHeading eyebrow="Current situation" title="Active alerts" detail="Official notices currently affecting communities in the network." action={<span className="font-mono text-[10px] text-muted-foreground">{alerts.length} {alerts.length === 1 ? 'notice' : 'notices'}</span>} />
      <div className="mb-5 flex flex-wrap gap-2"><div className="relative min-w-[210px] flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by place or event" className="field pl-9" aria-label="Search active alerts" data-testid="input-search-alerts" /></div>{['all', 'coastal', 'inland'].map((item) => <button key={item} onClick={() => setFilter(item)} className={`btn ${filter === item ? 'btn-primary' : 'btn-ghost'}`} data-testid={`button-filter-${item}`}><Filter size={14} />{item[0].toUpperCase() + item.slice(1)}</button>)}</div>
      {query.isLoading ? <LoadingBlock /> : query.isError ? <ErrorBlock onRetry={() => query.refetch()} /> : alerts.length === 0 ? <EmptyBlock title="No active notices" body="There are no verified alerts for this area right now. Check back here for live updates." /> : <div className="grid gap-4 sm:grid-cols-2">{alerts.map((alert, index) => <div key={alert.id} className={`rise-in delay-${Math.min(index + 1, 4)}`}><PublicAlertCard alert={alert} onOpen={() => setSelected(alert)} /></div>)}</div>}
      {selected && <div className="mt-5"><DetailPanel alert={selected} onClose={() => setSelected(null)} /></div>}
    </div><aside className="space-y-4"><div className="card-surface rounded-xl p-5"><div className="mb-5 flex items-center justify-between"><p className="eyebrow">How to use this feed</p><Info size={16} className="text-primary" /></div><div className="space-y-5">{[['01', 'Read the source', 'Every notice is issued by a named authority.'], ['02', 'Follow the guidance', 'Response steps are written for the affected area.'], ['03', 'Share the signal', 'Use official channels so information stays intact.']].map(([n, title, body]) => <div key={n} className="flex gap-3"><span className="font-mono text-[10px] text-accent">{n}</span><div><p className="text-xs font-extrabold">{title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{body}</p></div></div>)}</div></div><div className="rounded-xl border border-primary/20 bg-secondary/50 p-5"><div className="flex items-center gap-2 text-sm font-extrabold"><MapPinned size={16} className="text-primary" /> Your local signal</div><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Alerts are currently filtered to the North Coast coordination area.</p><button className="mt-4 flex items-center gap-1 text-xs font-extrabold text-primary" data-testid="button-change-area">Change area <ArrowUpRight size={13} /></button></div></aside></div>
  </div></AppShell>;
}